export enum ApiUriEnum {
  SIGNIN = 'account/signin',
  SIGNUP = 'account/signup',
  ACCOUNT_CREATE = 'account/create',
  ME = 'account/me',
  REFRESH_TOKEN = 'account/refresh',
  HELLO_WORLD = 'hello-world',

  //Employee
  EMPLOYEE_LIST = 'employee/list',
  EMPLOYEE_DETAIL = 'employee/detail/',
  EMPLOYEE_CREATE = 'employee/create',
  EMPLOYEE_UPDATE = 'employee/update',
  EMPLOYEE_DELETE = 'employee/delete/',
  EMPLOYEE_DELETED_LIST = 'employee/deleted',
  EMPLOYEE_SOFTDELETE = 'employee/softdelete/',
  EMPLOYEE_ROLLBACK = 'employee/rollbackdelete/',
  EMPLOYEE_ERASE = 'employee/erase/',

  //Parameter
  PARAMETER_LIST = 'param/list',
  PARAMETER_DETAIL = 'param/detail/',
  PARAMETER_CREATE = 'param/create',
  PARAMETER_UPDATE = 'param/update',
  PARAMETER_DELETE = 'param/delete/',
  PARAMETER_DELETED_LIST = 'param/deleted',
  PARAMETER_SOFTDELETE = 'param/softdelete/',
  PARAMETER_ROLLBACK = 'param/rollbackdelete/',
  PARAMETER_ERASE = 'param/erase/',

  //PrestationType
  PRESTATIONTYPE_LIST = 'prestationType/list',
  PRESTATIONTYPE_DETAIL = 'prestationType/detail/',
  PRESTATIONTYPE_CREATE = 'prestationType/create',
  PRESTATIONTYPE_UPDATE = 'prestationType/update',
  PRESTATIONTYPE_DELETE = 'prestationType/delete/',
  PRESTATIONTYPE_DELETED_LIST = 'prestationType/deleted',
  PRESTATIONTYPE_SOFTDELETE = 'prestationType/softdelete/',
  PRESTATIONTYPE_ROLLBACK = 'prestationType/rollbackdelete/',
  PRESTATIONTYPE_ERASE = 'prestationType/erase/',

  //Prestation
  PRESTATION_LIST   = 'prestation/list',
  PRESTATION_DETAIL = 'prestation/detail/',
  PRESTATION_CREATE = 'prestation/create',
  PRESTATION_UPDATE = 'prestation/update',
  PRESTATION_DELETE = 'prestation/delete/',
  PRESTATION_DELETED_LIST = 'prestation/deleted',
  PRESTATION_SOFTDELETE = 'prestation/softdelete/',
  PRESTATION_ROLLBACK = 'prestation/rollbackdelete/',
  PRESTATION_ERASE = 'prestation/erase/',

  //Address
  ADDRESS_LIST = 'address/list',
  ADDRESS_DELETED_LIST = 'address/deleted',
  ADDRESS_DETAIL = 'address/detail/',
  ADDRESS_CREATE = 'address/create',
  ADDRESS_UPDATE = 'address/update',
  ADDRESS_SOFTDELETE = 'address/softdelete/',
  ADDRESS_ROLLBACK = 'address/rollbackdelete/',
  ADDRESS_ERASE = 'address/erase/',

  //PrestationType
  GENERATORTEMPLATE_LIST   = 'generatorTemplate/list',
  GENERATORTEMPLATE_DETAIL = 'generatorTemplate/detail/',
  GENERATORTEMPLATE_CREATE = 'generatorTemplate/create',
  GENERATORTEMPLATE_UPDATE = 'generatorTemplate/update',
  GENERATORTEMPLATE_DELETE = 'generatorTemplate/delete/',
  GENERATORTEMPLATE_DELETED_LIST = 'generatorTemplate/deleted',
  GENERATORTEMPLATE_SOFTDELETE = 'generatorTemplate/softdelete/',
  GENERATORTEMPLATE_ROLLBACK = 'generatorTemplate/rollbackdelete/',
  GENERATORTEMPLATE_ERASE = 'generatorTemplate/erase/',

  //Role
  ROLE_LIST   = 'role/list',
  ROLE_DETAIL = 'role/detail/',
  ROLE_CREATE = 'role/create',
  ROLE_UPDATE = 'role/update',
  ROLE_DELETE = 'role/delete/',
  ROLE_DELETED_LIST = 'role/deleted',
  ROLE_SOFTDELETE = 'role/softdelete/',
  ROLE_ROLLBACK = 'role/rollbackdelete/',
  ROLE_ERASE = 'role/erase/',

  //Control
  CONTROL_LIST = 'control/list',
  CONTROL_DETAIL = 'control/detail/',
  CONTROL_CREATE = 'control/create',
  CONTROL_UPDATE = 'control/update',
  CONTROL_DELETE = 'control/delete/',
  CONTROL_DELETED_LIST = 'control/deleted',
  CONTROL_SOFTDELETE = 'control/softdelete/',
  CONTROL_ROLLBACK = 'control/rollbackdelete/',
  CONTROL_ERASE = 'control/erase/',

  //Planning
  PLANNING_LIST = 'planning/list',
  PLANNING_DETAIL = 'planning/detail/',
  PLANNING_CREATE = 'planning/create',
  PLANNING_UPDATE = 'planning/update',
  PLANNING_DELETE = 'planning/delete/',
  PLANNING_DELETED_LIST = 'planning/deleted',
  PLANNING_SOFTDELETE = 'planning/softdelete/',
  PLANNING_ROLLBACK = 'planning/rollbackdelete/',
  PLANNING_ERASE = 'planning/erase/',

  //Team
  TEAM_LIST = 'team/list',
  TEAM_LIST_HERITAGE = 'team/listHeritage',
  TEAM_DETAIL = 'team/detail/',
  TEAM_CREATE = 'team/create',
  TEAM_UPDATE = 'team/update',
  TEAM_DELETE = 'team/delete/',
  TEAM_DELETED_LIST = 'team/deleted',
  TEAM_SOFTDELETE = 'team/softdelete/',
  TEAM_ROLLBACK = 'team/rollbackdelete/',
  TEAM_ERASE = 'team/erase/',

  //Remember
  REMEMBER_LIST = 'remember/list',
  REMEMBER_DETAIL = 'remember/detail/',
  REMEMBER_CREATE = 'remember/create',
  REMEMBER_UPDATE = 'remember/update',
  REMEMBER_DELETE = 'remember/delete/',
  REMEMBER_DELETED_LIST = 'remember/deleted',
  REMEMBER_SOFTDELETE = 'remember/softdelete/',
  REMEMBER_ROLLBACK = 'remember/rollbackdelete/',
  REMEMBER_ERASE = 'remember/erase/',

  //History
  HISTORY_LIST = 'history/list',
  HISTORY_DETAIL = 'history/detail/',
  HISTORY_CREATE = 'history/create',
  HISTORY_UPDATE = 'history/update',
  HISTORY_DELETE = 'history/delete/',
  HISTORY_DELETED_LIST = 'history/deleted',
  HISTORY_SOFTDELETE = 'history/softdelete/',
  HISTORY_ROLLBACK = 'history/rollbackdelete/',
  HISTORY_ERASE = 'history/erase/',

  //History
  PERMISSION_LIST = 'permission/list',
  PERMISSION_DETAIL = 'permission/detail/',
  PERMISSION_CREATE = 'permission/create',
  PERMISSION_UPDATE = 'permission/update',
  PERMISSION_DELETE = 'permission/delete/',
  PERMISSION_DELETED_LIST = 'permission/deleted',
  PERMISSION_SOFTDELETE = 'permission/softdelete/',
  PERMISSION_ROLLBACK = 'permission/rollbackdelete/',
  PERMISSION_ERASE = 'permission/erase/',
}
